### ISSUE TITLE
Editor In Firefox - Spaces trimmed while typing

### ISSUE THREAD

**Issue by zbecknell** [telerik/kendo-react#270]
## I'm submitting a...

Bug Report.

## Current behavior

When attempting to type a sentence in the editor in Firefox 67.0.2, the spaces are trimmed as the next character is typed following the space.

## Expected behavior

Spaces are not trimmed when entered.

## Minimal reproduction of the problem with instructions

Behavior occurs in the [React Editor demo](https://www.telerik.com/kendo-react-ui/components/editor/).

## Environment

Package versions:

This occurs in the latest version -- the version number below comes from the Telerik demo.

```
"@progress/kendo-react-editor": "3.2.0"
```

Browser:
- Firefox version 67.0.2

(Behavior is not exhibited in Chrome, Safari, or Edge.)

System:
- Platform: Mac, Windows

**Comment by simonssspirit** [comment]
@zbecknell I was able to test and confirm this issue.

@nstoychev  Please take a look at it.

**Comment by nstoychev** [comment]
It looks like that an [Input Rule](https://prosemirror.net/docs/ref/#inputrules) which replace each space into `&nbsp;` character will resolve the issue - https://stackblitz.com/edit/react-zbqfrk-vxfy1m?file=app%2Fmain.jsx.

**Comment by zbecknell** [comment]
Thanks for the workaround, @nstoychev.  This gets us up and running for now.

**Comment by nstoychev** [comment]
@zbecknell - Fixed in version `3.3.0-dev.201906251221`.
https://stackblitz.com/edit/react-zbqfrk-v7ivv5?file=app/main.jsx

**Comment by zbecknell** [comment]
Thank you @nstoychev!

**Comment by Teshikajin** [comment]
@nstoychev the suggested solution gives interesting behavior when typing in the middle of a word when content was set using defaultContent property, you can see this in both of your examples. 

A reproduction scenario is to change KendoReact to Kendo React in the given text of your examples and then backspacing, you should notice that you will still have the a space between KendoReact. Is there an alternative input rule that will fix this case?

**Comment by nstoychev** [comment]
@Teshikajin I will check it. The input rule should be applied only it the inserted space is at the end of block element.

**Comment by zbecknell** [comment]
Do you think there will be a solution that adds a normal space rather than a non-breaking space?

**Comment by Teshikajin** [comment]
Further investigation has pointed out the problem doesn't seem to lie with the character but more with the how the rule is applied. It it seems to interpret a space in the middle of the word as the end of the line there by making it a non-breaking space, if continue typing after that space it correctly creates a normal space. so when evaluating the string it does not consider the entire "paragraph" but only the content up to the point of the space, a.k.a. the assumption is that you only add spaces as you type add not afterwards.

**Comment by nstoychev** [comment]
Since the fix which we have published at 3.3.0-dev.201906251221 version does not resolve the issue, we have decided to revert it.

@Teshikajin - Yes, I concluded the same. I have changed the input rule to match only the end of the text but the problem about deleting the spaces with backspace still exists https://stackblitz.com/edit/react-zbqfrk-y6w4pb?file=app/main.jsx.

@zbecknell - there is a solution which adds normal spaces. It requires to add 'white-space: pre-wrap' style to the editor's content. However after adding this style, the formatting applied by AlignJustify tool will be ignored by the browser (https://github.com/ProseMirror/prosemirror/issues/857).
Here is how to add the white-space style to the editor - https://stackblitz.com/edit/react-vqpopc?file=app/main.jsx
You should also make sure that there aren't unnecessary spaces in the HTML content.

**Comment by bradengc-github** [comment]
Has there been any progress in fixing this issue? The Editor is still non-functional for typing text in Firefox out of the box.

**Comment by stephangiesen** [comment]
I have the same problem with version kendo-react-editor": "^3.12.0"

**Comment by simonssspirit** [comment]
Reported again in ticket 1463804

**Comment by simonssspirit** [comment]
Reported in ticket: 1464752

**Comment by nstoychev** [comment]
Here is another solution - https://stackblitz.com/edit/react-xyvsew?file=app%2Fmain.jsx.
If it pass the tests, we can publish it soon.

**Comment by nstoychev** [comment]
Fixed in [3.15.0-dev.202005211105](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3150-dev202005211105).

Example - https://www.telerik.com/kendo-react-ui-develop/components/editor/
